### ISSUE TITLE
TPSP CR / 6 de Sept

### ISSUE THREAD

**Issue by alero0d** [krrrunch/todoparasuspies#106]
_Home:_

- [x] Banner distinto al de México (apenas se va a mandar) ¿existe esa posibilidad desde la plataforma?

- [x] Cambiar textos (igual que en México) más los cambios que aquí se enlisten.

_Bolsa de trabajo:_
- [x] Quitar bolsa de trabajo

_Contacto:_
- [x]  Corregir teléfono de contacto y donde salga(506) 83 94 64 30

_Noticias:_

- [x] Los mismos cambios que México.

Productos:

- [x] Mismos cambios que México, pero los botones dicen Comprar en tienda y vincular a buscar la tienda

_Servicios:_
- [x] Los mismos cambios que en México

_Sucursales:_
- [x] Mismos cambios y cuestiones que México, (que se pueda lograr la llamada cuando den de alta la plataforma).

_Generales:_
- [x] Actualizar los avisos de privacidad de TPSP y el otro formulario.

**Comment by jesaa** [comment]
Si existe la posibilidad de tener un banner para cada idioma

**Comment by alero0d** [comment]
_Bolsa de trabajo_

- [ ] Texto para abajo de titulo: 


- [ ] La caja de contacto se va a trabajar como un pop up, es decir se va a ver la descripción del trabajo y tendrá un botón de call to action que dice "Aplica" y es cuando sale el pop: up (está perfecto el que diseñaron ya).

- [ ] En vez de "descripción en dos renglones" poner: Háblanos de ti (2 renglones)

- [ ] En la leyenda fija abajo de cada aplicación en vez de: "Datos para mandar CV 
analistarh@todoparasuspies.com Tel: 36412000 ext 117,129 y 118 Lic. Claudia Gomez" por: Manda tu CV a: analistarh@todoparasuspies.com ó llama al (33)3641-2000 ext 117,129 y 118, con el titulo de la vacante en el asunto.

- [ ]

**Comment by alero0d** [comment]
- [ ] Cambios titulo de productos por: Más de 82 años innovando para el bienestar de tus pies y manos.

**Comment by alero0d** [comment]
> Más cambios

- [ ] En vez de titulo de productos poner:
