### ISSUE TITLE
Aparentemente listado de productos no está respetando adecuadamente los ajustes de height

### ISSUE THREAD

**Issue by mikemotion** [krrrunch/todoparasuspies#12]
Debe estar todo dentro de un width máximo y height máximo cuadrado.

*Revisar que también esté funcionando correctamente el width.

![untitled-10](https://cloud.githubusercontent.com/assets/2985080/16127544/90cd695a-33c2-11e6-813f-121075a5f7fe.png)

**Comment by mikemotion** [comment]
Otro ejemplo del error.

![untitled-3](https://cloud.githubusercontent.com/assets/2985080/16128263/9c760bba-33c5-11e6-8e31-89d204d3d32a.png)

**Comment by leoserick** [comment]
La imagen cuadrada es mas pequeña que la de la botella en la vertical realmente se esta respetando el espacio
