### ISSUE TITLE
Ajustar verticales en la vista de productos

### ISSUE THREAD

**Issue by mikemotion** [krrrunch/todoparasuspies#14]
Ajustar el margen de entre los productos y el wrapper del video para que coincida con el que se muestra en cada fila de productos.

![untitled-4](https://cloud.githubusercontent.com/assets/2985080/16128682/55c415d4-33c7-11e6-9536-967873f78ce6.png)

**Comment by leoserick** [comment]
@mikemotion con respecto a I? la imagen es mas pequeña que el contenedor .
