### ISSUE TITLE
Campos Bolsa de Trabajo

### ISSUE THREAD

**Issue by alero0d** [krrrunch/todoparasuspies#38]
- [x] Formulario: @mikemotion @jesaa 

- Puesto
- Área
-  Descripción
- Sueldo
- Notas
- Datos para mandar CV: Nombre del área, teléfono y correo

**Comment by jesaa** [comment]
@mikemotion La bolsa de trabajo va ir vinculada con las sucursales? ¿o sera general? Saldrán todas las vacantes o se podrán filtrar por tienda, ciudad y estado

**Comment by mikemotion** [comment]
Todas las vacantes en una lista. No hay clasificación por zonas.
