### ISSUE TITLE
Generar vista template

### ISSUE THREAD

**Issue by mikemotion** [krrrunch/todoparasuspies#41]
Que incluya todos los elementos para generar las vistas de las secciones.

**Comment by alero0d** [comment]
VISTAS POR TERMINAR @mikemotion 

- [ ]  Vista de Productos General (cuando escoges los 3)
- [ ]  Vista de Productos específica (Comfort, tratamiento o prevención)
- [ ] [ ] Vista de Servicios General
- [ ] Vista de Servicios: Pedicure Pro-Salud / Manicure Especial / Pedicure Infantil / Masaje Relajante
- [ ]  Afinar el localizador de tiendas: País, ciudad y sucursal (una ciudad tiene varias sucursales

SUBMENÚ
- [ ]  Nosotros
- [ ] Alianzas
- [ ] Bolsa de trabajo
- [ ] Franquicias
- [ ] Noticias
- [ ] Carrito
