### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by alero0d** [krrrunch/todoparasuspies#60]
- [x] Enlazar redes sociales pendientes: Youtube: https://www.youtube.com/channel/UC_Isub0CgYXzwxCNmFxvycg
Instagram: https://www.instagram.com/todoparasuspies/

- [x] Que las redes sociales se vean en todas las vistas.

- [x] Poner acento en selecciones su Región (ón)

- [x] Hasta abajo en donde dice"© 2016 - Todo para sus pies" Debe ser: © 2016 - Todo para sus Pies®

- [x] Issue se abra en otra página nueva (sección noticias)

- [x] Revisar alineados en el footer entre párrafos y en la tercera columna agregar OTROS como título de esa sección.

- [x] Cambiar título en la parte de productos quitar "Otras marcas en TPSP®" poner Otros productos

- [x] Reemplazar el texto del footer "© 2016 - Todo para sus pies®" por "© 2016 - Todo para sus Pies®" (Falta la "P" mayuscula en pies) @jesaa

**Comment by leoserick** [comment]
Me quede con la duda de si ibamos a pasar en el footer la parte de "Selecciona tu region" hasta abajo con las banderita.
